### PR TITLE
Adds missing HERE API module and CDN download automation

### PR DESCRIPTION
**Pull request by zor-el**
1. The package was missing the 'places' module
2. I also added a Rakefile that updates the local files from the remote sources to ease future updates.

### CODE REVIEW

**Comment by denyo** [comment]
Nice one. Thank you!
I didn't know about the `places.js` since I always got the service from the platform as described here https://developer.here.com/documentation/maps/topics_api/h-service-placesservice.html

Could you also extend the docs about the new module and perhaps how to execute the Rakefile?

**Comment by zor-el** [comment]
Yes, that link describes to use

```js
var places = platform.getPlacesService();
```

But without the places module, it didn't work for me.

**Comment by zor-el** [comment]
Docs updates. Could you make a new release / deploy to npm so I can switch back to the official package?

**Comment by denyo** [comment]
Thanks. Already did like 10 minutes ago.

**Pull request merged**
